### ISSUE TITLE
Error in readChar(con, 11) : invalid UTF-8 input

### ISSUE THREAD

**Issue by fjtaberner40** [tdanker/ephys2#1]
Hi,
I'm trying to get the tree info with get_treeinfo(), and it works really nice for some files and not for others. In this case I get the always the same error (Error in readChar(con, 11) : invalid UTF-8 input). What all the files that fail have got in common is that I have use a double amplifier, while the ones that open come from a single amplifier. Is there any work around to solve this problem?

Thanks a lot for such a nice tool.

Best

Francisco

**Comment by tdanker** [comment]
Hi Frederico, 
Can I have a data file from the double amplifier?

**Comment by fjtaberner40** [comment]
Hi tdanker,

here you have.
[double_amp_file.dat.zip](https://github.com/tdanker/ephys2/files/2973696/double_amp_file.dat.zip)

Thanks

**Comment by tdanker** [comment]
suprisingly, I can read the file here. 
I did: 
```r
tr<-get_treeinfo("double_amp_file.dat") 
s<-getSeries(tr,1,1,1) 
s$plot() 
```
and I can see the pot (spikes)

**Comment by fjtaberner40** [comment]
I have restarted Rstudio and executed the commands as you suggested but still the same problem with the files coming from this double amplifier. While no problem with the files coming from single amplifier. If it works well to you I get it should be something with my Rstudio or R version (3.5.1 in a Mac).
I'll try to install the most recent R version and see what happens.

Thanks

<img width="898" alt="Captura de pantalla 2019-03-16 a las 11 05 01" src="https://user-images.githubusercontent.com/16747330/54473710-c92b9f80-47db-11e9-8578-72cf7c94dea0.png">

**Comment by tdanker** [comment]
I doubt that this will solve the problem...
OsX and  linux have a different native enoding compared to windows, which affects reading the file. 
Was the file written on a Mac or on Windows? Is this different for the single amp and the double amp file?

**Comment by fjtaberner40** [comment]
Hi
the files (both single and double) were generated in Windows. I know there are some differences between double and single amplifier files because of the configuration of Patchmaster. But it should not be that important because it works in your hands.
