### ISSUE TITLE
Vmon and Adc0 traces

### ISSUE THREAD

**Issue by fjtaberner40** [tdanker/ephys2#2]
Hi,

In my series in addition to Imon traces, I've got Vmon or Adc0 traces. the you execute get series and you brows the object, you can find the that these information exist but I can not see the corresponding traces anywhere. Is it possible to retrieve this info, I would like to use it to align the Icon traces to stimulus.

Thanks in advance

Francisco

**Comment by tdanker** [comment]
getSeries has a trace parameter - does this work? 
try something like: 
`getSeries(tree,1,1,1,trace=2)`

**Comment by fjtaberner40** [comment]
It worked like a champ.
Thanks
